name: CI | Test Worker

# Requires the following secrets:
# - RUNPOD_ENDPOINT: The endpoint of the Runpod API
# - RUNPOD_API_KEY: The API key to authenticate with the Runpod API
# - GH_PAT: A GitHub Personal Access Token with access to the repository
# - GH_ORG: The GitHub organization the repository is in

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  initialize_worker:
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.extract_id.outputs.runpod_job_id }}

    steps:
      - name: Deploy Worker
        id: deploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.runpod.ai/v2/${{ secrets.RUNPOD_ENDPOINT }}/run"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.RUNPOD_API_KEY }}
          data: '{"input":{"github_pat": "${{ secrets.GH_PAT }}", "github_org":"${{ secrets.GH_ORG }}"}}'

      - name: Extract Job ID
        id: extract_id
        run: |
          ID=$(echo '${{ steps.deploy.outputs.response }}' | jq -r '.id')
          echo "::set-output name=runpod_job_id::$ID"

  run_tests:
    needs: initialize_worker
    runs-on: runpod

    steps:
      - uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          apt-get update -y
          apt-get upgrade -y
          apt-get install -y git ffmpeg libgl1-mesa-glx libglib2.0-0
          apt-get autoremove -y
          apt-get clean -y
          rm -rf /var/lib/apt/lists/*

      - name: Set up Python 3.11 & install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Install deforum-stable-diffusion
        run: |
          git clone https://github.com/justinmerrell/deforum-stable-diffusion.git
          cd deforum-stable-diffusion
          git reset --hard 3358d9aea454302f895f9f37f2344515c76a0adf
        env:
          PYTHONPATH: "${PYTHONPATH}:/deforum-stable-diffusion/src"

      - name: Copy files from src to deforum-stable-diffusion
        run: |
          cp -r src/* /deforum-stable-diffusion/

      - name: Cache Models
        run: |
          python builder/cache_models.py

      - name: Create symlink
        run: |
          ln -s /deforum-stable-diffusion/models /deforum-stable-diffusion/diffusion_models_cache

      - name: Execute Tests
        run: |
          python /deforum-stable-diffusion/rp_handler.py --test_input='{"input": {"animation_prompts": "0: a beautiful ball, trending on Artstation | 5: a beautiful monkey, trending on Artstation", "max_frames": 10}'

  terminate_worker:
    if: ${{ always() && !success() }}
    needs: initialize_worker
    runs-on: ubuntu-latest

    steps:
      - name: Shutdown Worker
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.runpod.ai/v2/${{ secrets.RUNPOD_ENDPOINT }}/cancel/${{ needs.initialize_worker.outputs.id }}"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.RUNPOD_API_KEY }}
